version: '1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 5432:5432
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=hemanshu
      - KEYCLOAK_ADMIN_PASSWORD=hemanshu
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://192.168.0.120:5432/digital_lending_keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=hemanshu
    command: ["start-dev"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/8080'"]
      interval: 10s
      retries: 10
      timeout: 5s


  userservice:
    depends_on:
      keycloak:
        condition: service_healthy
      registry:
        condition: service_healthy
      userdb:
        condition: service_healthy
#    restart: always
    image: hemanshu16/userservice
    ports:
      - 8083:8083
    environment:
      - DB_URL=jdbc:postgresql://192.168.0.120:5432/digital_lending_keycloak
      - USER_DB_URL=jdbc:postgresql://userdb:5432/digital_lending_user
      - DB_USER=postgres
      - DB_PASSWORD=hemanshu
      - server-url=http://keycloak:8080
      - eureka=http://registry:8081/eureka

  registry:
    image: hemanshu16/serviceregistry
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '>/dev/tcp/localhost/8081'" ]
      interval: 5s
      retries: 10
      timeout: 5s

  gateway:
    image: hemanshu16/apigatewayservice
    ports:
      - 8082:8082
    depends_on:
      registry:
        condition: service_healthy
    environment:
      - ISSUER-URI=http://keycloak:8080/realms/myRealm
      - INTROSPECTION_URI=http://keycloak:8080/realms/myRealm/protocol/openid-connect/token/introspect
      - CLIENT_ID=springboot
      - CLIENT_SECRET=6i94LmuHoqnw8I5kNSYvPD9Je6VIhNYU
      - eureka=http://registry:8081/eureka


  userdb:
    image: postgres:16
    volumes:
      - postgres_data_userdb1:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: digital_lending_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hemanshu
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

volumes:
  postgres_data_userdb1: